export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const LOAD_TEST_SCENARIOS_SUCCESS= 'LOAD_TEST_SCENARIOS_SUCCESS';
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS';
export const SEARCH_TEST_SCENARIOS_SUCCESS = 'SEARCH_TEST_SCENARIOS_SUCCESS';

export const DRILLDOWN_SUCCESS = 'DRILLDOWN_SUCCESS'; 